name: Generate README.md
on:
  push:
    paths:
      - 'service/*'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.1'
      - name: Generate README.md
        run: |
          ruby service/program.rb -i service/input.json -t service/template.md -o README.md
          
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update from $(git rev-parse --short=8 HEAD)" || :
          git push || :
